name: flutter_segment
description: Flutter implementation of Segment Analytics for iOS, Android and Web
version: 4.1.0
homepage: https://www.claimsforce.com
repository: https://github.com/claimsforce-gmbh/flutter-segment
issue_tracker: https://github.com/claimsforce-gmbh/flutter-segment/issues
documentation: https://github.com/claimsforce-gmbh/flutter-segment#readme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: 1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_segment
        pluginClass: FlutterSegmentPlugin
      ios:
        pluginClass: FlutterSegmentPlugin
      web:
        pluginClass: SegmentWeb
        fileName: src/segment_web.dart
